In [7]:
import numpy as np

In [8]:
v=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
print(v)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print(v. T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [10]:
a = np.random.random((3, 3))

In [11]:
b=np.random.random((3, 3))

In [12]:
a

array([[0.86991302, 0.63835396, 0.13094245],
       [0.2920102 , 0.66558307, 0.40906417],
       [0.12475139, 0.3547874 , 0.02193378]])

In [13]:
b

array([[0.76977612, 0.80519642, 0.88721877],
       [0.81852933, 0.82695551, 0.04369131],
       [0.38141945, 0.14936773, 0.91962917]])

In [14]:
print(v @ (v. T))

[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


In [16]:
a=np.array([[1,2,3],[2,3,4],[5,5,6],[5,6,7]])

In [17]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [5, 5, 6],
       [5, 6, 7]])

In [21]:
a.shape

(4, 3)

In [22]:
print(a.shape)

(4, 3)


In [25]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [26]:
A=np.zeros((3,3))

In [27]:
A

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
A.shape

(3, 3)

In [29]:
A[0][1]=5

In [30]:
A

array([[0., 5., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
b=np.ones((2,2))

In [32]:
b

array([[1., 1.],
       [1., 1.]])

In [33]:
x=b.T

In [34]:
x

array([[1., 1.],
       [1., 1.]])

In [35]:
A.T

array([[0., 0., 0.],
       [5., 0., 0.],
       [0., 0., 0.]])

In [38]:
I=np.eye((2)) #identity matrix er jnno parameter ekta!!!!!!!!!!!!!

In [39]:
I

array([[1., 0.],
       [0., 1.]])

In [40]:
np.full((2,2),10)


array([[10, 10],
       [10, 10]])

In [53]:
R=np.random.random((5,5))
print("Random Value\n", R)
print("--------------------------------#---------------------------------------------------")
A=10
EM=A * R
print("Eliment-wise multiplication \n",EM)
EM=np.multiply(A,R)
print("Another way to elimentwise Multiply \n",EM)

Random Value
 [[0.43437624 0.8511136  0.47918363 0.47854928 0.49389306]
 [0.96694627 0.70394469 0.0543043  0.18395369 0.83156075]
 [0.97675288 0.26882526 0.59930586 0.05044969 0.86051623]
 [0.2765139  0.48025168 0.0969135  0.4432185  0.24968189]
 [0.98248465 0.35013048 0.25364578 0.95727149 0.30329623]]
--------------------------------#---------------------------------------------------
Eliment-wise multiplication 
 [[4.34376239 8.51113598 4.79183629 4.78549284 4.93893064]
 [9.66946267 7.03944691 0.54304297 1.83953691 8.31560752]
 [9.76752879 2.68825258 5.99305861 0.50449693 8.60516228]
 [2.765139   4.80251678 0.96913504 4.43218498 2.49681894]
 [9.82484654 3.50130483 2.53645782 9.57271489 3.03296229]]
Another way to elimentwise Multiply 
 [[4.34376239 8.51113598 4.79183629 4.78549284 4.93893064]
 [9.66946267 7.03944691 0.54304297 1.83953691 8.31560752]
 [9.76752879 2.68825258 5.99305861 0.50449693 8.60516228]
 [2.765139   4.80251678 0.96913504 4.43218498 2.49681894]
 [9.82484654 3.5013