In [ ]:
import numpy as np
import torch

In [ ]:
a=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x=torch.rand((3,3))
x

tensor([[0.8093, 0.5641, 0.5194],
        [0.0467, 0.2210, 0.8028],
        [0.2429, 0.7802, 0.2793]])

In [ ]:
b=torch.randn((3,3))
b

tensor([[-0.4475,  0.1232,  1.0795],
        [ 2.6415,  0.8766, -0.5109],
        [ 1.5228, -0.3619,  0.0444]])

In [ ]:
z=a.t() #a.T
z

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [ ]:
y=x @ b
y

tensor([[ 1.9187,  0.4063,  0.6085],
        [ 1.7855, -0.0910, -0.0268],
        [ 2.3776,  0.6128, -0.1241]])

In [ ]:
R = np.array([[2, 3, 6, 7, 4],
              [3, 5, 7, 9, 10],
              [6, 7, 8, 9, 12]])
R=print(R[-2:-1,-2:])


[[ 9 10]]


In [ ]:
t = torch.Tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

t

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
print(t[-2:-1,-2:-1])
print(t[0:2:2,0:2:2])


tensor([[5.]])
tensor([[1.]])
